name: Trigger auto deployment for container-app-m4jsb224mfxmk

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/container-app-m4jsb224mfxmk-AutoDeployTrigger-910cbb86-2be8-47eb-ae3a-e9aa0fef602a.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: containerregistrym4jsb224mfxmk.azurecr.io
          username: ${{ secrets.CONTAINERAPPM4JSB224MFXMK_REGISTRY_USERNAME }}
          password: ${{ secrets.CONTAINERAPPM4JSB224MFXMK_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: containerregistrym4jsb224mfxmk.azurecr.io/container-app-m4jsb224mfxmk:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.CONTAINERAPPM4JSB224MFXMK_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n container-app-m4jsb224mfxmk -g pethotel8b69 --server containerregistrym4jsb224mfxmk.azurecr.io --username  ${{ secrets.CONTAINERAPPM4JSB224MFXMK_REGISTRY_USERNAME }} --password ${{ secrets.CONTAINERAPPM4JSB224MFXMK_REGISTRY_PASSWORD }}
            az containerapp update -n container-app-m4jsb224mfxmk -g pethotel8b69 --image containerregistrym4jsb224mfxmk.azurecr.io/container-app-m4jsb224mfxmk:${{ github.sha }}
